### PR TITLE
Add elapsed attribute to ReturnEvent.

### PR DESCRIPTION
**Pull request by virajkanwade**
Need to figure out how to fix unit test as elapsed time could be different every time.

### CODE REVIEW

**Comment by virajkanwade** [comment]
@apotterri please do review the commits (merge can wait). I will try and fix the unit tests as and when I get some time. Any suggestions on how to mock elapsed time as it would change everytime.

**Comment by apotterri** [comment]
I would say it's not necessary to test for any specific value of the  `elapsed_time` attribute. Just checking to make sure it's present is enough. Updating the [normalize](https://github.com/applandinc/appmap-python/blob/master/appmap/test/test_recording.py#L50) function and the [expected appmap](https://github.com/applandinc/appmap-python/blob/master/appmap/test/data/expected.appmap.json) should do it.

**Comment by ptrdvrk** [comment]
Hello @virajkanwade,

Thank you so much for being an awesome contributor to this project!

We are asking our external contributors to sign a Contributor License Agreement in order to ensure that our projects remain licensed under Free and Open Source licenses. It is a common practice that many open source projects follow, including Apache SF projects, Python, Django and many others. You can find details about the CLA and its execution [here](https://github.com/applandorg/community/blob/master/docs/CLA%20Instructions.pdf).

Please sign the CLA electronically at your convenience here: [https://app.hellosign.com/s/AQT1lZWI](https://app.hellosign.com/s/AQT1lZWI)

With Kind Regards,
Petr, Product @ Appland

**Comment by apotterri** [comment]
@virajkanwade This PR and your git metadata PR look good to me. Have you had a chance to look at the CLA @ptrdvrk mentioned above?  Once that gets signed, we'll be able to move forward with these changes.

Thanks!

**Comment by virajkanwade** [comment]
@apotterri @ptrdvrk I have sent it to legal. Will let you know as soon as I hear back from them.

**Comment by ptrdvrk** [comment]
Thank you for the update @virajkanwade . Let me know if I can be of any assistance during the review.

**Comment by virajkanwade** [comment]
@apotterri @ptrdvrk signed.

**Comment by apotterri** [comment]
> @apotterri @ptrdvrk signed.

Great, thanks very much.

Please add an entry to the CHANGELOG log for these changes (as well as #25) and tidy up the history. Once that's done, I'll go ahead and merge both.

Thanks again.

**Comment by ptrdvrk** [comment]
Thank you @virajkanwade!

**Comment by virajkanwade** [comment]
@apotterri PR #30 for getting the changelog upto speed. Once both #24  and #25 are merged, we can update the changelog and set tag

**Comment by apotterri** [comment]
#30 is merged. Both #24 and #25 now show merge conflicts. Can you rebase them, please, and update the CHANGELOG for each. That will keep all the related updates together.

**Comment by virajkanwade** [comment]
@apotterri please merge #24 first then #25

**Review by apotterri — APPROVED** [review]

**Pull request merged**
