### PR TITLE
Preset labels for known library functions

### PR DESCRIPTION
**Pull request by dividedmind**
Just the infrastructure. Specific labels for more libraries to come.

### CODE REVIEW

**Comment by dividedmind** [comment]
One thing I couldn't decide: do you think the presence of a label declaration should automatically cause the function to be recorded? appmap-ruby does this (I believe). In appmap-python currently labeling and recording are separate settings -- the functions still need to be added to the config file `packages` field.

**Review by apotterri — APPROVED** [review]
Looks good, thanks.

**Comment by apotterri** [comment]
> One thing I couldn't decide: do you think the presence of a label declaration should automatically cause the function to be recorded? appmap-ruby does this (I believe). In appmap-python currently labeling and recording are separate settings -- the functions still need to be added to the config file `packages` field.

I don't know what appmap-ruby's behavior is. Following whatever it does seems fine to me.

**Comment by kgilpin** [comment]
`appmap-ruby` doesn't automatically record anything that's labeled. It would have to parse every source file of every Gem and that seems infeasible.

**Comment by dividedmind** [comment]
> `appmap-ruby` doesn't automatically record anything that's labeled. It would have to parse every source file of every Gem and that seems infeasible.

But doesn't it always hook and record whatever has labels defined on in `hooks`?

**Comment by kgilpin** [comment]
Yes, it does do that. I thought you meant it would record any source file
with @label

**Pull request merged**
